title: Danielle Whitfield 
logo: "/images/profile-image.png?raw=true" 
description: >
  <br> I'm a technical writer with over four years of experience writing and edition documentation for software validation and customer use. I have extensive experience with 
  Microsoft tools included Microsoft Word and Excel, as well as other writing tools such as AsciiDoc, Visual Studio Code, and LaTeX. <br>
  <br>This portfolio contains sample of my technical writing work, including customer-facing documentation and academic projects.<br>
  <br>
  
  <a href="https://github.com/dwhitfield233" target="_blank">View my Github Page</a>
  <br><br>
  <a href="https://www.linkedin.com/in/danielle-whitfield-569257140/" target="_blank">View My LinkedIn Profile</a> 
  <br>
  
theme: jekyll-theme-minimal

