title: Danielle Whitfield 
logo: "/images/profile-image.png?raw=true" 
description: >
  <br>A sample of my technical writing work, including customer-facing documentation and academic work.<br>
  <br>
  
  <a href="https://github.com/dwhitfield233">View my Github Page</a>
  <br>
  <a href="https://www.linkedin.com/in/danielle-whitfield-569257140/">View My LinkedIn Profile</a> 
  <br>
  
theme: jekyll-theme-minimal

